### ISSUE TITLE
Make jquery migrate plugin optional via projectConfig.json

### ISSUE THREAD

**Issue by smohadjer** [virtualidentityag/frontend-framework#14]

**Comment by janrembold** [comment]
I think jQuery (and its migrate plugin) is part of the project specific scripts include and is not related to any general configuration. I would recommend to leave it as demo and for initial quality assurance in the framework.

**Comment by smohadjer** [comment]
jQuery is, but not its migrate plugin.

**Comment by janrembold** [comment]
Oh, you are talking about the npm include via package.json not the projectConfig.json. I agree with that

**Comment by janrembold** [comment]
https://github.com/virtualidentityag/frontend-framework/pull/17
