### ISSUE TITLE
Rename "global" variable to something less generic

### ISSUE THREAD

**Issue by smohadjer** [virtualidentityag/frontend-framework#16]
We should use a less generic name for our global variable to reduce the chance of collision with external scripts. In a recent project our use of "global" caused client's tracking code to stop functioning due to namespace collision. I suggest "viglobal". 

Note that gulp framework should also be updated so that handlebars namespace also uses the new variable name.

**Comment by timomayer** [comment]
viglobal or ffglobal (frontend framework) if we dont want to have the vi name inside of a variable name
