### ISSUE TITLE
Discussion: Do we need the linting for LF/CRLF in eslint?

### ISSUE THREAD

**Issue by alxbenz** [virtualidentityag/frontend-framework#5]
When cloning this repository with default git settings in windows, user will get errors when using gulp serve/build. 
Do we event need this warning. In my opinion git should be able to hande the line feeds in files automatically. Therefore i think we should remove the following from eslintrc

`"linebreak-style": [
      2,
      "unix"
    ],`

**Comment by timomayer** [comment]
+1 i had the same problem with the new boilerplate.

**Comment by janrembold** [comment]
Disabled linebreak-style error in eslint: https://github.com/virtualidentityag/frontend-framework/commit/51095e34e82f24b419ee6e24c6c5d72b3efa6f94
